Toolbar Headline
yayaismaail/portf pull request #1
Opened 2023-07-03 16:56 UTC by yayaismaail

In this Project I:

- set up linters
- update README file
- added index.html and styles.css files and 
- built header/toolbar and headline of the portfolio

NOTE: the web hint is not included in the linters because it is not working and we were told to remove the configurations

2023-07-03 18:45 UTC, algerina requested changes
Hi @yayaismaail  ,

Great job so far! 

May I highlight the following: 
- [x] Your work is clean and well organized👏  ✔️ 
- [x] Your project looks awesome✔️ 
- [x] Well done deploying already your Portfolio✔️ 




## STATUS: CHANGES REQUIRED:muscle::clap:


<img src="https://media4.giphy.com/media/neUaH5fz6ZpefE2KBP/giphy.gif"/>
 
 ## Optional suggestions

- [ optional] Your commits are descriptive however it is recommended to use Imperative mood , so instead of "updated Readme" you can use "Update Readme instead".

 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2023-07-03 18:45 UTC, algerina commented on index.html
> +            <a href="#" class="my-logo">MY LOGO</a>
- [ Optional] I will recomend you to use your own Logo or create one, it will look more professional.

2023-07-03 18:45 UTC, algerina commented on index.html
> +                <span class="bar"></span>
- [ ] The hamburger button should be on the right and has a `nav` tag. The `nav` tag is for semantics reason, and the right position for convention and user experience for mobile devices. I recommend putting your logo outside of the Nav.

2023-07-03 18:45 UTC, algerina commented on styles.css
> +  /* height: 100%; */
- [ ] I recommend deleting commented lines of code, your work is well organized it will look perfect.

2023-07-03 18:45 UTC, algerina commented on README.md
> +
- [ ] Since your already deployed your project, please add the link to the Readme.

2023-07-04 11:19 UTC, yayaismaail commented on index.html
> +            <a href="#" class="my-logo">MY LOGO</a>
@algerina, thank you for your wonderful review, but in the curriculum we were told to replicate the chosen template that is why I used it (MY LOGO) 👍

2023-07-04 11:20 UTC, yayaismaail commented on styles.css
> +  /* height: 100%; */
@algerina, accept my deepest thanks

2023-07-04 11:20 UTC, yayaismaail commented on README.md
> +
@algerina, 😆

2023-07-04 11:39 UTC, AlphaNtihinduka requested changes
## Hi @yayaismaail 🙋‍♂️
Good job working on implementing the changes required by the previous reviewer. You have done the design to do the expectation and incredibly well. 👏  

TO HIGHLIGHT:
- Your work is clean and well organized👏 ✔️
- Your project looks awesome✔️
- Well done deploying already your Portfolio✔️
- Well-structured files ✅

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

## Required changes :recycle: 
- _Kindly consider the inline review comments ☺️._

## Optional suggestions
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

2023-07-04 11:39 UTC, AlphaNtihinduka commented on README.md
> +
- [ ] As suggested by the previous reviewer, kindly consider adding the live demo link of the application. You should not leave any section of the readme empty ☺️.

2023-07-04 12:40 UTC, yayaismaail commented on README.md
> +
@AlphaNtihinduka, 👍

2023-07-04 12:50 UTC, divinecharlotte approved these changes
# Hello @yayaismaail       😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say  👍🏻 ✅ 
### To Highlight 💯


- Descriptive commit messages👍 
- Good implementation of the required changes 👍 
 




## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers, and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-04 12:55 UTC, merged